# Generated by Django 4.1.2 on 2022-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(choices=[("OTHER", "Other")], default="OTHER", max_length=8),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("place", models.CharField(max_length=64)),
                ("team", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=1024)),
            ],
        ),
    ]
