# Generated by Django 4.1.2 on 2022-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="end",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="start",
        ),
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="end_time",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="start_time",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
