# Generated by Django 4.1.2 on 2022-10-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_remove_event_activities_remove_event_partakers"),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.activity",
                    ),
                ),
                ("possible_points", models.IntegerField(default=0)),
            ],
            bases=("activity.activity",),
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.activity",
                    ),
                ),
            ],
            bases=("activity.activity",),
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.activity",
                    ),
                ),
                ("points_min", models.IntegerField(default=0)),
            ],
            bases=("activity.activity",),
        ),
        migrations.AddField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
            preserve_default=False,
        ),
    ]
