# Generated by Django 4.1.2 on 2022-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_remove_activity_end_remove_activity_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(max_length=64),
        ),
    ]
