# Generated by Django 4.1.2 on 2022-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("partaker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("description", models.CharField(max_length=1024)),
                (
                    "activities",
                    models.ManyToManyField(related_name="event", to="activity.activity"),
                ),
                ("partakers", models.ManyToManyField(related_name="event", to="partaker.partaker")),
            ],
        ),
    ]
