# Generated by Django 4.1.2 on 2022-10-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="event",
            name="partakers",
        ),
    ]
