# Generated by Django 4.1.2 on 2022-11-02 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "partaker_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partaker.partaker",
                    ),
                ),
                ("discord", models.CharField(blank=True, max_length=64)),
                ("Telegram", models.CharField(blank=True, max_length=64)),
            ],
            bases=("partaker.partaker",),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "partaker_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partaker.partaker",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partaker.team"
                    ),
                ),
                ("members", models.ManyToManyField(to="partaker.team")),
            ],
            bases=("partaker.partaker",),
        ),
    ]
