# Generated by Django 4.1.2 on 2022-10-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_remove_event_activities_remove_event_partakers"),
        ("partaker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "partaker_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partaker.partaker",
                    ),
                ),
                ("discord", models.CharField(max_length=64)),
                ("Telegram", models.CharField(max_length=64)),
            ],
            bases=("partaker.partaker",),
        ),
        migrations.AddField(
            model_name="partaker",
            name="event",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "partaker_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partaker.partaker",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partaker.team"
                    ),
                ),
                ("members", models.ManyToManyField(to="partaker.team")),
            ],
            bases=("partaker.partaker",),
        ),
    ]
