# Generated by Django 4.1.3 on 2022-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_category'),
        ('event', '0001_initial'),
        ('partaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partaker',
            name='activities',
            field=models.ManyToManyField(to='activity.activity'),
        ),
        migrations.RemoveField(
            model_name='partaker',
            name='event',
        ),
        migrations.AddField(
            model_name='partaker',
            name='event',
            field=models.ManyToManyField(to='event.event'),
        ),
    ]
