# Generated by Django 4.1.3 on 2022-11-27 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        ("activity", "0003_alter_activity_category"),
        ("partaker", "0002_partaker_activities_remove_partaker_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partaker",
            name="event",
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "player_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partaker.player",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="activity.activity"
                    ),
                ),
            ],
            bases=("partaker.player",),
        ),
        migrations.AddField(
            model_name="partaker",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
            ),
            preserve_default=False,
        ),
    ]
